name: three_js_geometry
description: "Flutter three_js_geometry package converted from threejs and three_dart package created for three_js."
version: 0.1.1
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js_geometry

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_core:
    path: ../three_js_core/
    version: any
  three_js_math:
    path: ../three_js_math/
    version: any
  three_js_curves:
    path: ../three_js_curves/
    version: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
